name: Unit tests
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            target: ${{ matrix.target }}
            override: true
            components: rustfmt, clippy

      - name: Unit tests (std)
        run: cargo test --no-default-features --features std
      - name: Unit tests (alloc)
        run: cargo test --no-default-features --features alloc
